loopback_inf0: Loopback0

sonic_interfaces:
   - name: "{{ spine_r1l1_inf1 }}"
     description: "{{ spine_r1l1_inf1 }} r1-leaf-a"
     enabled: true
   - name: "{{ spine_r1l2_inf2 }}"
     description: "{{ spine_r1l2_inf2 }} r1-leaf-b"
     enabled: true
   - name: "{{ spine_r2l1_inf3 }}"
     description: "{{ spine_r2l1_inf3 }} r2-leaf-a"
     enabled: true
   - name: "{{ spine_r2l2_inf4 }}"
     description: "{{ spine_r2l2_inf4 }} r2-leaf-b"
     enabled: true
   - name: "{{ loopback_inf0 }}"

sonic_l3_interfaces:
   - name: "{{ loopback_inf0 }}"
     ipv4:
      addresses:     
        - address: "{{ loopback0_ip }}"
   - name: "{{ spine_r1l1_inf1 }}"
     ipv6:
       enabled: true
   - name: "{{ spine_r1l2_inf2 }}"
     ipv6:
       enabled: true
   - name: "{{ spine_r2l1_inf3 }}"
     ipv6:
       enabled: true
   - name: "{{ spine_r2l2_inf4 }}"
     ipv6:
       enabled: true

sonic_bgp:
   - bgp_as: "{{ bgp_asn }}"
     router_id: "{{ loopback0_ip.split('/')[0] }}"
     bestpath:
       as_path:
         multipath_relax: true

sonic_bgp_af:
    - bgp_as: "{{ bgp_asn }}"
      address_family:
        afis:
          - afi: l2vpn
            safi: evpn
            advertise_all_vni: true
          - afi: ipv4
            safi: unicast
            redistribute:
              - protocol: connected

sonic_bgp_neighbors:
    - bgp_as: "{{ bgp_asn }}"
      peer_group:
        - name: LEAF
          remote_as:
            peer_type: external
          advertisement_interval: 5
          timers:
            keepalive: 3
            holdtime: 9
          bfd: true
          capability:
            extended_nexthop: true
          address_family:
            afis:
              - afi: l2vpn
                safi: evpn
                activate: true
              - afi: ipv4
                safi: unicast
                activate: true          
      neighbors:
        - neighbor: "{{ spine_r1l1_inf1 }}"
          peer_group: LEAF
        - neighbor: "{{ spine_r1l2_inf2 }}"
          peer_group: LEAF
        - neighbor: "{{ spine_r2l1_inf3 }}"
          peer_group: LEAF
        - neighbor: "{{ spine_r2l2_inf4 }}"
          peer_group: LEAF
